In [1]:
import pandas as pd

In [2]:
cancer_mapping = {
    'ACC': 0, 'BLCA': 1, 'BRCA': 2, 'CESC': 3, 'CHOL': 4, 'CNTL': 5,
    'COAD': 6, 'DLBC': 7, 'ESCA': 8, 'FPPP': 9, 'GBM': 10, 'HNSC': 11,
    'KICH': 12, 'KIRC': 13, 'KIRP': 14, 'LAML': 15, 'LCML': 16, 'LGG': 17,
    'LIHC': 18, 'LUAD': 19, 'LUSC': 20, 'MESO': 21, 'MISC': 22, 'OV': 23,
    'PAAD': 24, 'PCPG': 25, 'PRAD': 26, 'READ': 27, 'SARC': 28, 'SKCM': 29,
    'STAD': 30, 'TGCT': 31, 'THCA': 32, 'THYM': 33, 'UCEC': 34, 'UCS': 35,
    'UVM': 36
}

inv_mapping = {v: k for k, v in cancer_mapping.items()}

In [3]:

# Load the CSV file
file_path = '/home/chb3333/yulab/chb3333/gem-patho/models/actual_final_results/only_genetics/all_batch/cancertypebatching_exp_1_phase2_0/global_test_cindices.csv'
df = pd.read_csv(file_path)

# Add a new column 'cancer_name' by mapping the numeric cancer_type to its corresponding name
df['cancer_name'] = df['cancer_type'].map(inv_mapping)

# Calculate the average of the 'c_index' column
mean_c_index = df['c_index'].mean()
print("Average c_index:", mean_c_index)

# Filter rows where c_index is over 0.55
filtered_df = df[df['c_index'] > 0.55]

# Count the number of rows with a c_index above 0.55
count_over = len(filtered_df)

# Calculate the average of the c_index values for those rows
average_over = filtered_df['c_index'].mean()

print("Count of c_index values over 0.55:", count_over)
print("Average c_index for values over 0.55:", average_over)

# Optionally, display the first few rows to see the cancer names alongside the indices
print(df.head())

Average c_index: 0.5296881298618622
Count of c_index values over 0.55: 12
Average c_index for values over 0.55: 0.6269998900802896
   cancer_type   c_index cancer_name
0            8  0.472605        ESCA
1            2  0.521543        BRCA
2           10  0.482185         GBM
3           12  0.466368        KICH
4           11  0.493500        HNSC

In [4]:
df

    cancer_type   c_index cancer_name
0             8  0.472605        ESCA
1             2  0.521543        BRCA
2            10  0.482185         GBM
3            12  0.466368        KICH
4            11  0.493500        HNSC
5            17  0.713443         LGG
6            15  0.546457        LAML
7            13  0.504341        KIRC
8            20  0.536463        LUSC
9            19  0.575302        LUAD
10            6  0.450303        COAD
11            7  0.731915        DLBC
12            3  0.502350        CESC
13            4  0.570234        CHOL
14            1  0.551383        BLCA
15            0  0.670308         ACC
16           21  0.472740        MESO
17           18  0.478779        LIHC
18           35  0.603006         UCS
19           36  0.596154         UVM
20           14  0.640058        KIRP
21           26  0.650900        PRAD
22           28  0.495443        SARC
23           27  0.525991        READ
24           23  0.536013          OV
25           33  0.310169        THYM
26           25  0.610256        PCPG
27           32  0.337069        THCA
28           30  0.497232        STAD
29           31  0.310850        TGCT
30           24  0.500725        PAAD
31           29  0.514583        SKCM
32           34  0.611040        UCEC

In [5]:
filtered_df

    cancer_type   c_index cancer_name
5            17  0.713443         LGG
9            19  0.575302        LUAD
11            7  0.731915        DLBC
13            4  0.570234        CHOL
14            1  0.551383        BLCA
15            0  0.670308         ACC
18           35  0.603006         UCS
19           36  0.596154         UVM
20           14  0.640058        KIRP
21           26  0.650900        PRAD
26           25  0.610256        PCPG
32           34  0.611040        UCEC

In [5]:
# Replace with your actual file path
file_path = '/home/chb3333/yulab/chb3333/gem-patho/models/actual_final_results/only_genetics/all_batch/cancertypebatching_exp_0_phase2_10/global_test_cindices.csv'

# Load the CSV file
df = pd.read_csv(file_path)

# Calculate the average of the 'c_index' column
mean_c_index = df['c_index'].mean()

print("Average c_index:", mean_c_index)


filtered_df = df[df['c_index'] > 0.55]

# Count how many rows have a c_index above 0.55
count_over = len(filtered_df)

# Calculate the average of the c_index values for those rows
average_over = filtered_df['c_index'].mean()

print("Count of c_index values over 0.55:", count_over)
print("Average c_index for values over 0.55:", average_over)

Average c_index: 0.5203056081475042
Count of c_index values over 0.55: 9
Average c_index for values over 0.55: 0.6095490517579581

In [7]:
# Replace with your actual file path
file_path = '/home/chb3333/yulab/chb3333/gem-patho/models/actual_final_results/only_genetics/ct_batch/cancertypebatching_exp_0_warmup_0/global_test_cindices.csv'

# Load the CSV file
df = pd.read_csv(file_path)

# Calculate the average of the 'c_index' column
mean_c_index = df['c_index'].mean()

print("Average c_index:", mean_c_index)

filtered_df = df[df['c_index'] > 0.55]

# Count how many rows have a c_index above 0.55
count_over = len(filtered_df)

# Calculate the average of the c_index values for those rows
average_over = filtered_df['c_index'].mean()

print("Count of c_index values over 0.55:", count_over)
print("Average c_index for values over 0.55:", average_over)

Average c_index: 0.5226164238168604
Count of c_index values over 0.55: 9
Average c_index for values over 0.55: 0.6135951810103613

In [8]:
# Replace with your actual file path
file_path = '/home/chb3333/yulab/chb3333/gem-patho/models/actual_final_results/only_genetics/ct_batch/cancertypebatching_exp_1_warmup_10/global_test_cindices.csv'

# Load the CSV file
df = pd.read_csv(file_path)

# Calculate the average of the 'c_index' column
mean_c_index = df['c_index'].mean()

print("Average c_index:", mean_c_index)

filtered_df = df[df['c_index'] > 0.55]

# Count how many rows have a c_index above 0.55
count_over = len(filtered_df)

# Calculate the average of the c_index values for those rows
average_over = filtered_df['c_index'].mean()

print("Count of c_index values over 0.55:", count_over)
print("Average c_index for values over 0.55:", average_over)

Average c_index: 0.5026486252094335
Count of c_index values over 0.55: 7
Average c_index for values over 0.55: 0.5859032838482753

In [9]:
# Replace with your actual file path
file_path = '/home/chb3333/yulab/chb3333/gem-patho/models/clean_baseline_results/pure_genetics/one_hot_encoded/global_test_cindices.csv'

# Load the CSV file
df = pd.read_csv(file_path)

# Calculate the average of the 'c_index' column
mean_c_index = df['c_index'].mean()

print("Average c_index:", mean_c_index)

filtered_df = df[df['c_index'] > 0.55]

# Count how many rows have a c_index above 0.55
count_over = len(filtered_df)

# Calculate the average of the c_index values for those rows
average_over = filtered_df['c_index'].mean()

print("Count of c_index values over 0.55:", count_over)
print("Average c_index for values over 0.55:", average_over)

Average c_index: 0.5226525500353183
Count of c_index values over 0.55: 9
Average c_index for values over 0.55: 0.5978077820904698

In [10]:
filtered_df

   cancer_type   c_index
1         BRCA  0.589470
5          LGG  0.652346
11        DLBC  0.578723
17        LIHC  0.565203
21        PRAD  0.559383
27        THCA  0.599532
29        TGCT  0.639296
30        PAAD  0.587992
32        UCEC  0.608325

In [11]:
df

   cancer_type   c_index
0         ESCA  0.498442
1         BRCA  0.589470
2          GBM  0.523126
3         KICH  0.524664
4         HNSC  0.481182
5          LGG  0.652346
6         LAML  0.515842
7         KIRC  0.542540
8         LUSC  0.502151
9         LUAD  0.546306
10        COAD  0.462197
11        DLBC  0.578723
12        CESC  0.503150
13        CHOL  0.423077
14        BLCA  0.532142
15         ACC  0.471698
16        MESO  0.538020
17        LIHC  0.565203
18         UCS  0.528736
19         UVM  0.479783
20        KIRP  0.496114
21        PRAD  0.559383
22        SARC  0.474979
23        READ  0.453165
24          OV  0.540386
25        THYM  0.436441
26        PCPG  0.415385
27        THCA  0.599532
28        STAD  0.495219
29        TGCT  0.639296
30        PAAD  0.587992
31        SKCM  0.482519
32        UCEC  0.608325

In [12]:
# Replace with your actual file path
file_path = '/home/chb3333/yulab/chb3333/gem-patho/models/improved_fusing/layer_norm_fusion_mlp/cancertypebatching_exp_0_phase2_10/global_test_cindices.csv'

# Load the CSV file
df = pd.read_csv(file_path)

# Calculate the average of the 'c_index' column
mean_c_index = df['c_index'].mean()

print("Average c_index:", mean_c_index)

filtered_df = df[df['c_index'] > 0.55]

# Count how many rows have a c_index above 0.55
count_over = len(filtered_df)

# Calculate the average of the c_index values for those rows
average_over = filtered_df['c_index'].mean()

print("Count of c_index values over 0.55:", count_over)
print("Average c_index for values over 0.55:", average_over)

Average c_index: 0.5986890387697241
Count of c_index values over 0.55: 22
Average c_index for values over 0.55: 0.6363075135619731

In [14]:
filtered_strict_df = df[df['c_index'] > 0.6]

# Count how many rows have a c_index above 0.6
count_over = len(filtered_strict_df)

# Calculate the average of the c_index values for those rows
average_over = filtered_strict_df['c_index'].mean()

print("Count of c_index values over 0.60:", count_over)
print("Average c_index for values over 0.60:", average_over)

Count of c_index values over 0.60: 12
Average c_index for values over 0.60: 0.68348210286405

In [16]:
df['cancer_name'] = df['cancer_type'].map(inv_mapping)

In [18]:
print(df)

    cancer_type   c_index cancer_name
0             8  0.529083        ESCA
1             2  0.604596        BRCA
2            10  0.519909         GBM
3            12  0.730942        KICH
4            11  0.597086        HNSC
5            17  0.656863         LGG
6            15  0.503476        LAML
7            13  0.678942        KIRC
8            20  0.523102        LUSC
9            19  0.523012        LUAD
10            6  0.546188        COAD
11            7  0.812766        DLBC
12            3  0.537454        CESC
13            4  0.565217        CHOL
14            1  0.575301        BLCA
15            0  0.742304         ACC
16           21  0.576399        MESO
17           18  0.592325        LIHC
18           35  0.541114         UCS
19           36  0.548323         UVM
20           14  0.677461        KIRP
21           26  0.461697        PRAD
22           28  0.591798        SARC
23           27  0.610396        READ
24           23  0.524615          OV
25           33  0.681356        THYM
26           25  0.721026        PCPG
27           32  0.663433        THCA
28           30  0.557071        STAD
29           31  0.621701        TGCT
30           24  0.562215        PAAD
31           29  0.580065        SKCM
32           34  0.599502        UCEC